### ISSUE TITLE
Is it any other settings that is needed

### ISSUE THREAD

**Issue by alekslyse** [Dnkhatri/Avistaz-Subtitle-Downloader#1]
I see in the code its some empty fields

torrent_directory=
cookie_directoy=
torrent_processed=

Could you update the readme or tell me lightly what to put there and I can make a PR with abit more detailed information?

**Comment by Dnkhatri** [comment]
These settings are needed it works for me mostly so I stopped improving it. As I use it with sonarr I have delayed the torrent download by 2 hours in sonarr. Which gives ample time for subtitles to be uploaded for new episodes. 

avistaz.sh "%N" "%D" "%R"   you need to run the script in run external program on torrent added in qbittorrent

torrent_directory="copy .torrent file to " set the directory that in qbittorrent settings and in the file
cookie_directory="you need to extract avistaz cookie from chrome cookies and point to it"
torrent_processed="this is the directory where the .torrent are moved to once processed by the script"

**Comment by alekslyse** [comment]
So  in other words you let qbt run this script at completion, and let sonarr wait two hours before grabbing the downloaded file?

**Comment by Dnkhatri** [comment]
no sonarr adds the torrent to qbittorrent after 2 hours. As the subtitle is downloaded as soon as the torrent is added to qbittorrent

**Comment by alekslyse** [comment]
Do you mind showing me with a photo or text how you did it?

With best regards,
Aleksander Lyse

**Comment by Dnkhatri** [comment]
> > for what sonarr?
> 
> Yes, just give a short tutoral how you set it up with sonarr / qbt

Sonarr has nothing to do with the script it just runs in qbittorrent and work when any torrent is added to qbittorrent

![Screenshot from 2023-07-18 03-27-42](https://github.com/Dnkhatri/Avistaz-Subtitle-Downloader/assets/7855682/5e857932-86f1-430e-b706-a50c0631265f)
![Screenshot from 2023-07-18 03-28-18](https://github.com/Dnkhatri/Avistaz-Subtitle-Downloader/assets/7855682/9ce252c1-8ce3-4e98-97fa-f1b830c994db)

**Comment by Dnkhatri** [comment]
@alekslyse 
I have updated the script with some fixes and more details on how to run it.
